# Generated by Django 5.2.17 on 2026-09-01 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='banner_image_url',
            field=models.CharField(blank=True, default='https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80', max_length=500),
        ),
        migrations.AddField(
            model_name='destination',
            name='crime_data_source',
            field=models.CharField(choices=[('Real-Time', 'Real-Time API Feed'), ('Statistical', 'Statistical (Historical Records)'), ('Manual', 'Manual Authority Entry')], default='Statistical (Historical Records)', help_text='Source of the crime data displayed for this destination', max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='crime_trend',
            field=models.CharField(choices=[('Improving', 'Improving ↓'), ('Deteriorating', 'Deteriorating ↑'), ('Stable', 'Stable →')], default='Stable', help_text='Direction of the crime trend over the last 30 days', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='harassment_change_pct',
            field=models.FloatField(default=0.0, help_text='Percentage change in harassment reports'),
        ),
        migrations.AddField(
            model_name='destination',
            name='last_crime_update',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent crime data refresh', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='theft_change_pct',
            field=models.FloatField(default=0.0, help_text='Percentage change in theft reports (last quarter vs. previous)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='violent_crime_reports',
            field=models.IntegerField(default=1, help_text='Quarterly reported violent crime cases'),
        ),
        migrations.CreateModel(
            name='TourismPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier, auto-generated if left blank', max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline for the package card', max_length=300)),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('Weekend', 'Weekend Getaway'), ('Adventure', 'Adventure & Activity'), ('Cultural', 'Cultural & Heritage'), ('Luxury', 'Luxury Escape'), ('Budget', 'Budget Backpacker'), ('WomenSafe', 'Women-Safe Solo')], default='Cultural', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price in INR', max_digits=10)),
                ('duration_days', models.IntegerField(default=2, help_text='Length of the package in days')),
                ('rating', models.FloatField(default=4.5, help_text='Average customer rating (0-5)')),
                ('review_count', models.IntegerField(default=0, help_text='Total number of reviews')),
                ('highlights', models.JSONField(default=list, help_text='Key selling points of the package')),
                ('inclusions', models.JSONField(default=list, help_text='What is included (meals, transport, entry fees, etc.)')),
                ('exclusions', models.JSONField(default=list, help_text='What is NOT included')),
                ('itinerary_summary', models.JSONField(default=list, help_text='Day-wise high-level itinerary preview')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False, help_text='Showcase on landing page carousel')),
                ('is_available', models.BooleanField(default=True)),
                ('max_group_size', models.IntegerField(default=6, help_text='Maximum travelers per booking')),
                ('age_from', models.IntegerField(default=5, help_text='Minimum recommended age')),
                ('age_to', models.IntegerField(default=65, help_text='Maximum recommended age')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Challenging', 'Challenging')], default='Easy', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.destination')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTripReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(default='Anonymous Traveler', max_length=150)),
                ('traveler_type', models.CharField(choices=[('Solo Woman', 'Solo Woman Traveler'), ('Solo Man', 'Solo Man Traveler'), ('Family', 'Family Group'), ('Friends', 'Friends Group'), ('Couple', 'Couple'), ('Individual Traveler', 'Individual Traveler')], default='Individual Traveler', max_length=60)),
                ('overall_rating', models.FloatField(default=0.0, help_text='Overall trip rating (0-5)')),
                ('safety_rating', models.FloatField(default=0.0, help_text='Safety experience rating (0-5)')),
                ('value_rating', models.FloatField(default=0.0, help_text='Value for money rating (0-5)')),
                ('title', models.CharField(help_text='Review headline', max_length=200)),
                ('detailed_notes', models.TextField(blank=True, help_text='Detailed post-trip notes and reflections')),
                ('pros', models.JSONField(default=list, help_text='Positive aspects of the trip')),
                ('cons', models.JSONField(default=list, help_text='Areas for improvement')),
                ('travel_tips', models.TextField(blank=True, help_text='Tips for future travelers')),
                ('would_recommend', models.BooleanField(default=True, help_text='Would you recommend this destination?')),
                ('photos', models.JSONField(default=list, help_text='Photo URLs with captions [{url, caption}]')),
                ('is_published', models.BooleanField(default=False, help_text='Display publicly on destination page')),
                ('moderated', models.BooleanField(default=False, help_text='Review has been admin-approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_trip_reviews', to='core.destination')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_trip_reviews', to='core.tourismpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name (or Anonymous)', max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Optional — for follow-up', max_length=254)),
                ('category', models.CharField(choices=[('General', 'General Platform Feedback'), ('Destination', 'Destination Experience'), ('Safety', 'Safety / Crime Data Accuracy'), ('Hotel', 'Verified Hotel Experience'), ('Package', 'Tourism Package Experience'), ('App', 'App / UX Feedback')], default='General', max_length=50)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = Poor, 5 = Excellent')),
                ('subject', models.CharField(blank=True, help_text='Brief subject line', max_length=200)),
                ('message', models.TextField(help_text='Detailed feedback message')),
                ('contact_allowed', models.BooleanField(default=False, help_text='Allow follow-up contact?')),
                ('is_resolved', models.BooleanField(default=False, help_text='Internal status — feedback addressed')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When a team member responded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='core.destination')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='core.tourismpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrimeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text="e.g. 'Q1 2025', 'Jan 2026'", max_length=50)),
                ('recorded_at', models.DateField(help_text='Reporting period end date')),
                ('theft_cases', models.IntegerField(default=0)),
                ('harassment_cases', models.IntegerField(default=0)),
                ('violent_crime_cases', models.IntegerField(default=0)),
                ('other_cases', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField(default=0, help_text='Sum of all crime categories')),
                ('population_estimate', models.IntegerField(default=200000, help_text='Reference population for rate calculation')),
                ('crime_rate_per_100k', models.FloatField(default=0.0, help_text='Computed crime rate per 100k population')),
                ('data_source', models.CharField(default='Local Police Records', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_statistics', to='core.destination')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'unique_together': {('destination', 'period_label')},
            },
        ),
    ]
