# Generated by Django 5.2.17 on 2026-09-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_contact_email_booking_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_reference_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('traveler_name', models.CharField(default='Solo Traveler', max_length=150)),
                ('traveler_phone', models.CharField(blank=True, max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField(default=16.9891)),
                ('longitude', models.FloatField(default=81.784)),
                ('location_name', models.CharField(default='Godavari Riverfront', max_length=255)),
                ('jurisdiction_police_station', models.CharField(default='Rajahmundry I Town Police Station', max_length=200)),
                ('pcr_callsign', models.CharField(default='PCR-UNIT-1', max_length=100)),
                ('dispatch_status', models.CharField(choices=[('QUEUED', '⏳ ERSS 112 Queued'), ('DISPATCHED_TO_PCR', '🚔 PCR Unit Dispatched'), ('PCR_EN_ROUTE', '🚨 PCR Unit En Route'), ('ON_SCENE', '📍 First Responders On Scene'), ('RESOLVED', '✅ Incident Resolved & Safe')], default='DISPATCHED_TO_PCR', max_length=40)),
                ('cad_payload', models.JSONField(blank=True, default=dict)),
                ('is_offline_sync', models.BooleanField(default=False, help_text='Was this alert synced after being offline?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erss_dispatches', to='core.incidentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
